languageCode = 'en-us'
title = 'PHP Room at FrOSCon 2023'
theme = 'ananke'

[params]
featured_image = "images/elephants.jpg"

[[params.ananke_socials]]
name = "twitter"
url = "https://twitter.com/phpugcgn"

[[params.ananke_socials]]
name = "github"
url = "https://github.com/phpugcgn/froscon"
